INSERT INTO `bms`.`sys_dict` (`dict_id`, `p_id`, `dict_name`, `dict_value`, `description`, `order_num`, `is_enable`, `update_time`, `update_user`, `update_user_id`, `create_user_id`, `create_time`, `create_user`, `ext_1`, `ext_2`, `ext_3`, `ext_4`) 
VALUES ('campusGroup', '0', '校区组', NULL, NULL, '0', '1', '2018-05-23 10:45:10', NULL, NULL, NULL, '2018-05-23 10:45:10', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `bms`.`sys_dict` (`dict_id`, `p_id`, `dict_name`, `dict_value`, `description`, `order_num`, `is_enable`, `update_time`, `update_user`, `update_user_id`, `create_user_id`, `create_time`, `create_user`, `ext_1`, `ext_2`, `ext_3`, `ext_4`) 
VALUES ('campusGroup.1', 'campusGroup', '招生办校区', '1', NULL, '1', '1', '2018-05-23 10:47:45', NULL, NULL, NULL, '2018-05-23 10:47:45', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `bms`.`sys_dict` (`dict_id`, `p_id`, `dict_name`, `dict_value`, `description`, `order_num`, `is_enable`, `update_time`, `update_user`, `update_user_id`, `create_user_id`, `create_time`, `create_user`, `ext_1`, `ext_2`, `ext_3`, `ext_4`) 
VALUES ('campusGroup.2', 'campusGroup', '内勤校区', '2', NULL, '2', '1', '2018-05-23 10:48:39', NULL, NULL, NULL, '2018-05-23 10:48:39', NULL, NULL, NULL, NULL, NULL);



insert into `sys_dict` (`dict_id`, `p_id`, `dict_name`, `dict_value`, `description`, `order_num`, `is_enable`, `update_time`, `update_user`, `update_user_id`, `create_user_id`, `create_time`, `create_user`, `ext_1`, `ext_2`, `ext_3`, `ext_4`) values('stdStage.14','stdStage','休学学员','14',NULL,'14','1','2018-05-25 19:37:43',NULL,NULL,NULL,'2018-05-25 19:37:43',NULL,NULL,NULL,NULL,NULL);
insert into `sys_dict` (`dict_id`, `p_id`, `dict_name`, `dict_value`, `description`, `order_num`, `is_enable`, `update_time`, `update_user`, `update_user_id`, `create_user_id`, `create_time`, `create_user`, `ext_1`, `ext_2`, `ext_3`, `ext_4`) values('quitSchoolReason.6','quitSchoolReason','人在外地','6',NULL,'6','1','2018-05-25 11:33:00',NULL,NULL,NULL,'2018-05-25 11:33:00',NULL,NULL,NULL,NULL,NULL);
insert into `sys_dict` (`dict_id`, `p_id`, `dict_name`, `dict_value`, `description`, `order_num`, `is_enable`, `update_time`, `update_user`, `update_user_id`, `create_user_id`, `create_time`, `create_user`, `ext_1`, `ext_2`, `ext_3`, `ext_4`) values('quitSchoolReason.5','quitSchoolReason','身体原因','5',NULL,'5','1','2018-05-25 11:32:39',NULL,NULL,NULL,'2018-05-25 11:32:39',NULL,NULL,NULL,NULL,NULL);
insert into `sys_dict` (`dict_id`, `p_id`, `dict_name`, `dict_value`, `description`, `order_num`, `is_enable`, `update_time`, `update_user`, `update_user_id`, `create_user_id`, `create_time`, `create_user`, `ext_1`, `ext_2`, `ext_3`, `ext_4`) values('quitSchoolReason.4','quitSchoolReason','联系不上','4',NULL,'4','1','2018-05-25 11:32:18',NULL,NULL,NULL,'2018-05-25 11:32:18',NULL,NULL,NULL,NULL,NULL);
insert into `sys_dict` (`dict_id`, `p_id`, `dict_name`, `dict_value`, `description`, `order_num`, `is_enable`, `update_time`, `update_user`, `update_user_id`, `create_user_id`, `create_time`, `create_user`, `ext_1`, `ext_2`, `ext_3`, `ext_4`) values('quitSchoolReason.3','quitSchoolReason','经济困难','3',NULL,'3','1','2018-05-25 11:31:44',NULL,NULL,NULL,'2018-05-25 11:31:44',NULL,NULL,NULL,NULL,NULL);
insert into `sys_dict` (`dict_id`, `p_id`, `dict_name`, `dict_value`, `description`, `order_num`, `is_enable`, `update_time`, `update_user`, `update_user_id`, `create_user_id`, `create_time`, `create_user`, `ext_1`, `ext_2`, `ext_3`, `ext_4`) values('quitSchoolReason.2','quitSchoolReason','无法参考','2',NULL,'2','1','2018-05-25 11:31:25',NULL,NULL,NULL,'2018-05-25 11:31:25',NULL,NULL,NULL,NULL,NULL);
insert into `sys_dict` (`dict_id`, `p_id`, `dict_name`, `dict_value`, `description`, `order_num`, `is_enable`, `update_time`, `update_user`, `update_user_id`, `create_user_id`, `create_time`, `create_user`, `ext_1`, `ext_2`, `ext_3`, `ext_4`) values('quitSchoolReason.1','quitSchoolReason','统考原因','1',NULL,'1','1','2018-05-25 11:31:02',NULL,NULL,NULL,'2018-05-25 11:31:02',NULL,NULL,NULL,NULL,NULL);
insert into `sys_dict` (`dict_id`, `p_id`, `dict_name`, `dict_value`, `description`, `order_num`, `is_enable`, `update_time`, `update_user`, `update_user_id`, `create_user_id`, `create_time`, `create_user`, `ext_1`, `ext_2`, `ext_3`, `ext_4`) values('quitSchoolReason','0','休学原因',NULL,NULL,'0','1','2018-05-25 11:30:00',NULL,NULL,NULL,'2018-05-25 11:30:00',NULL,NULL,NULL,NULL,NULL);
