INSERT INTO `bms`.`sys_dict` (`dict_id`, `p_id`, `dict_name`, `dict_value`, `description`, `order_num`, `is_enable`, `update_time`, `update_user`, `update_user_id`, `create_user_id`, `create_time`, `create_user`, `ext_1`, `ext_2`, `ext_3`, `ext_4`) VALUES ('jtId.GKZL1', 'jtId', '国开资料初审', 'GKZL1', '初审', '110', '1', '2018-05-14 18:31:26', NULL, NULL, NULL, '2018-05-14 18:31:26', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `bms`.`sys_dict` (`dict_id`, `p_id`, `dict_name`, `dict_value`, `description`, `order_num`, `is_enable`, `update_time`, `update_user`, `update_user_id`, `create_user_id`, `create_time`, `create_user`, `ext_1`, `ext_2`, `ext_3`, `ext_4`) VALUES ('jtId.GKZL2', 'jtId', '国开资料二审', 'GKZL2', '二审', '111', '1', '2018-05-14 18:32:15', NULL, NULL, NULL, '2018-05-14 18:32:15', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `bms`.`sys_dict` (`dict_id`, `p_id`, `dict_name`, `dict_value`, `description`, `order_num`, `is_enable`, `update_time`, `update_user`, `update_user_id`, `create_user_id`, `create_time`, `create_user`, `ext_1`, `ext_2`, `ext_3`, `ext_4`) VALUES ('jtId.GKZL3', 'jtId', '国开资料三审', 'GKZL3', '三审', '112', '1', '2018-05-14 18:33:10', NULL, NULL, NULL, '2018-05-14 18:33:10', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `bms`.`sys_dict` (`dict_id`, `p_id`, `dict_name`, `dict_value`, `description`, `order_num`, `is_enable`, `update_time`, `update_user`, `update_user_id`, `create_user_id`, `create_time`, `create_user`, `ext_1`, `ext_2`, `ext_3`, `ext_4`) VALUES ('jtId.GKZL4', 'jtId', '国开资料终审', 'GKZL4', '终审', '113', '1', '2018-05-14 18:33:46', NULL, NULL, NULL, '2018-05-14 18:33:46', NULL, NULL, NULL, NULL, NULL);

insert into `bms`.`sys_dict` (`dict_id`, `p_id`, `dict_name`, `dict_value`, `description`, `order_num`, `is_enable`, `update_time`, `update_user`, `update_user_id`, `create_user_id`, `create_time`, `create_user`, `ext_1`, `ext_2`, `ext_3`, `ext_4`) values('inviteQrType','0','邀约页面',NULL,'邀约页面','0','1','2018-05-19 16:29:36',NULL,NULL,NULL,'2018-05-19 16:29:36',NULL,NULL,NULL,NULL,NULL);
insert into `bms`.`sys_dict` (`dict_id`, `p_id`, `dict_name`, `dict_value`, `description`, `order_num`, `is_enable`, `update_time`, `update_user`, `update_user_id`, `create_user_id`, `create_time`, `create_user`, `ext_1`, `ext_2`, `ext_3`, `ext_4`) values('inviteQrType.1','inviteQrType','常规邀约','https://test.yzwill.cn/invite','常规邀约','1','1','2018-05-19 16:32:56',NULL,NULL,NULL,'2018-05-19 16:32:56',NULL,NULL,NULL,NULL,NULL);
insert into `bms`.`sys_dict` (`dict_id`, `p_id`, `dict_name`, `dict_value`, `description`, `order_num`, `is_enable`, `update_time`, `update_user`, `update_user_id`, `create_user_id`, `create_time`, `create_user`, `ext_1`, `ext_2`, `ext_3`, `ext_4`) values('inviteQrType.2','inviteQrType','圆梦奖学金','https://test.yzwill.cn/active/dreamsScholarship','圆梦奖学金','2','1','2018-05-19 16:33:07',NULL,NULL,NULL,'2018-05-19 16:33:07',NULL,NULL,NULL,NULL,NULL);


INSERT INTO `bms`.`sys_dict` (`dict_id`, `p_id`, `dict_name`, `dict_value`, `description`, `order_num`, `is_enable`, `update_time`, `update_user`, `update_user_id`, `create_user_id`, `create_time`, `create_user`, `ext_1`, `ext_2`, `ext_3`, `ext_4`) VALUES ('checkType.12', 'checkType', '国开资料审核', '12', NULL, '12', '1', '2018-05-19 16:26:03', NULL, NULL, NULL, '2018-05-19 16:26:03', NULL, NULL, NULL, NULL, NULL);
